version: 2.1

orbs:
  node: circleci/node@16.15.1

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run cypress
      - run : 
          name : Run build
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .